version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/sudoku

    environment:
      MAVEN_OPTS: -Xmx2000m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - sudoku-dependencies-{{ checksum "pom.xml" }}
          - sudoku-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: sudoku-dependencies-{{ checksum "pom.xml" }}

      - run: mvn clean

      - run: mvn install

